topaniot/HomeAssistant_Packages

configuration_template.yaml, packages/server.yaml, packages/unavailable_entities.yaml, packages/updates_available.yaml, secrets_template.yaml
Aproba daca esti de acord cu modificarile. 
Fiserul de server inca nu e inclus in descarcarea automata.
=> server file

packages/unavailable_entities.yaml
modified trigger to exclude false positive when reloading only templates
=> modified trigger

packages/low_battery.yaml, packages/problems.yaml, packages/server.yaml, packages/unavailable_entities.yaml, packages/updates_available.yaml
=> Added problems notifications

packages/themes.yaml
Added ha-card-background to remove background on some themes.
=> added ha-card-background

packages/hacs.yaml, packages/open_window.yaml
the code is already tested in production server
=> add first version of open_windows

packages/low_battery.yaml, packages/problems.yaml, packages/unavailable_entities.yaml, packages/updates_available.yaml, packages/windows_and_doors.yaml, template_sensors.yaml
Fixed template errors due to device_class not defined for all entities.
Updated some sensors to search only on one domain.
Updated the frecvency of refreshing sensors.
=> Fix template

packages/server.yaml, packages/updates_available.yaml
- Removed uptime sensor because was migrated to interface.
- Increased login attempt threshold to 15
=> uptime and login atempt

packages/themes.yaml
Corrected no card background theme to match with 2022.11.
=> Corected no card backgroun theme

packages/server.yaml
=> Ram notify

packages/updates_available.yaml
Change update notifications with timer to improve long waiting time before notifying.
=> Updated updates notifications

packages/unavailable_entities.yaml
At the moments checks for sensors with device classes 'temperature','energy','window','door'.
=> Added unavailable sensors

packages/updates_available.yaml
avoid multiple noficiations when update more on the same time.
=> Add 5 seconds delay

packages/updates_available.yaml
move notification delay only when sensor is above 1
=> move delay

packages/server.yaml, packages/updates_available.yaml
=> Maintenance messages

packages/updates_available.yaml
condition >0 instead >1 to install also only one update
=> Bug fix >1

packages/updates_available.yaml
Changed ESPHome update method
Moved update notify service to input_text
Set default account when no account is set on input_text
=> ESPHome update method

packages/asuswrt.yaml, packages/hacs.yaml, packages/insights.yaml, packages/low_battery.yaml, packages/problems.yaml, packages/raspberrypi.yaml, packages/server.yaml, packages/themes.yaml, packages/unavailable_entities.yaml, packages/updates_available.yaml, packages/windows_and_doors.yaml
=> Replaced groups and secrets with Helpers

packages/server.yaml
Put installed updates at the begnning of the message
=> Changed messate for maintenance

packages/server.yaml
Added Webhook trigger for remote packages update
=> Webhook trigger for packages update

packages/unavailable_entities.yaml, packages/updates_available.yaml
- Added opening device class to unavailable sensors
- increased update delay for notifications esphome and firmware
=> Opening and delay

packages/low_battery.yaml
Add a positive 10 procent hysteresis
=> Improve notifications handling

packages/server.yaml
=> Disable IP ban

packages/updates_available.yaml
Old entity was update.esphome_update and new one is update.esphome_device_builder_update. I modified to include both.
=> Bugfix for esphome update

packages/updates_available.yaml
Increased majos update time for addons and hacs to be the same as core.
=> Increate major update time

packages/updates_available.yaml
Backup on update gives an error
=> Disable backup for core
